-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 10:53:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_db` DEFAULT CHARACTER SET utf8 ;
USE `default_db` ;

-- -----------------------------------------------------
-- Table `default_db`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_db`.`Students` (
  `Id` INT NOT NULL,
  `Full_Name` VARCHAR(128) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Date_Of_Birth` DATE NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Group` VARCHAR(45) NOT NULL,
  `Avatar` VARCHAR(128) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC),
  UNIQUE INDEX `Full_Name_UNIQUE` (`Full_Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_db`.`Сall_Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_db`.`Сall_Schedule` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Time` TIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  UNIQUE INDEX `Time_UNIQUE` (`Time` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_db`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_db`.`Subject` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_db`.`Schedule_Of_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_db`.`Schedule_Of_Items` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Subject` INT NOT NULL,
  `Id_Call_Schedule` INT NOT NULL,
  `Group` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  INDEX `fk_Schedule_Of_Items_Subject_idx` (`Id_Subject` ASC),
  INDEX `fk_Schedule_Of_Items_Сall_Schedule1_idx` (`Id_Call_Schedule` ASC),
  CONSTRAINT `fk_Schedule_Of_Items_Subject`
    FOREIGN KEY (`Id_Subject`)
    REFERENCES `default_db`.`Subject` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_Of_Items_Сall_Schedule1`
    FOREIGN KEY (`Id_Call_Schedule`)
    REFERENCES `default_db`.`Сall_Schedule` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
